services:
  - type: web
    name: portfolio-flask
    env: python
    pythonVersion: 3.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI